# Generated by Django 6.0.2 on 2026-03-02 16:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0003_recipe_author_recipe_created_on_recipe_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 2, 16, 56, 22, 364982, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 2, 16, 56, 22, 365144, tzinfo=datetime.timezone.utc)),
        ),
    ]
