# Generated by Django 6.0.2 on 2026-03-02 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_recipe_author_alter_recipe_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 2, 17, 40, 8, 745477, tzinfo=datetime.timezone.utc)),
        ),
    ]
