# Generated by Django 6.0.2 on 2026-03-12 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_recipe_created_on_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='image',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipe_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 10, 13, 3, 465178, tzinfo=datetime.timezone.utc)),
        ),
    ]
