# Generated by Django 6.0.2 on 2026-03-12 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_remove_recipeimage_image_recipeimage_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 12, 1, 50, 777015, tzinfo=datetime.timezone.utc)),
        ),
    ]
