# Generated by Django 6.0.2 on 2026-03-12 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_recipe_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 15, 45, 54, 165449, tzinfo=datetime.timezone.utc)),
        ),
    ]
